### ISSUE TITLE
Update requirements.txt 

### ISSUE THREAD

**Issue by tnniras** [kaushikjadhav01/Cancer-Donation-Portal-Python-Flask-App#2]
Hi Owner,

It seems the requirements.txt  file is created manually. I would recommend create file using below command and update.

`$ pip freeze  requirements.txt `

Why I'm asking this? There was error when I tried  installing  requirements.

```
ERROR: Could not find a version that satisfies the requirement sqlite3
ERROR: No matching distribution found for sqlite3
```

Thanks,
Tushar - tnniras@gmail.com

**Comment by kaushikjadhav01** [comment]
This is fixed now.
